members/urls.py
from django.urls import path

from . import views

app_name = 'members'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('new', views.CreateView.as_view(), name='create'),
  path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
  path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('members/', include('members.urls')),
    path('admin/', admin.site.urls),
]

members/models.py
from django.db import models

class Member(models.Model):
  message = models.CharField(max_length=200)

members/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Member

class IndexView(generic.ListView):
    template_name = 'members/index.html'
    context_object_name = 'member_list'

    def get_queryset(self):
      """Return all the members on the roster."""
      return Member.objects.all()

class CreateView(generic.edit.CreateView):
  template_name = 'members/create.html'
  model = Member
  fields = ['message']
  success_url = reverse_lazy('members:index')

class UpdateView(generic.edit.UpdateView):
    template_name = 'members/update.html'
    model = Member
    fields = ['message']
    success_url = reverse_lazy('members:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'members/delete.html'
    model = Member
    success_url = reverse_lazy('members:index')

members/templates/members/create.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

members/templates/members/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.message }}"?</p>
    <input type="submit" value="Confirm">
</form>

members/templates/members/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'members/styles.css' %}">

<h2>Members</h2>

{% if member_list %}
  <ul>
    {% for member in member_list %}
      <li>{{ member.message }}</li>
      <a href="{% url 'members:update' member.id %}">edit</a>
      <a href="{% url 'members:delete' member.id %}">delete</a>
    {% endfor %}
  </ul>
{% else %}
  <p>No members are enrolled at this time.</p>
{% endif %}
<a href="{% url 'members:create' %}">Enroll a New Member!</a>

members/templates/members/update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'members:delete' member.id %}">delete</a>
</form>